name: Deploy

on:
  push:

env:
  TZ: Asia/Tokyo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install NPM packages
        run: npm ci

      - name: Build app
        run: npm run build
        # env:
        #   URL_PREFIX: portfolio

        # GitHub Pagesはサーバーサイドのルーティングができないため、React Routerを使ったSPAでURLを直接指定すると404エラーになる。
        # GitHub Pagesの仕様で、存在しないパスは404.htmlにリダイレクトされる。から、index.htmlと同じ内容にすることでReact Routerがルーティングを処理できる。
      - name: 404.html for SPA routing on GitHub Pages
        run: cp dist/index.html dist/404.html

      - name: Generate sitemap
        run: npm run generate-sitemap

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          cname: turai.work
